In [1]:
%matplotlib inline

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
pd.set_option('display.max_columns', None)
pd.options.mode.chained_assignment = None

df = pd.read_csv("../Multi-Agent/data/train.csv")
df_val = pd.read_csv('../Multi-Agent/data/validation.csv')

In [2]:
df.head(n=3)

,click,weekday,hour,bidid,userid,useragent,IP,region,city,adexchange,domain,url,urlid,slotid,slotwidth,slotheight,slotvisibility,slotformat,slotprice,creative,bidprice,payprice,keypage,advertiser,usertag
0,0,5,22,b7bea80521fdecd95d2d761a38c91c3f09618066,2e880fb7d690cf7377b2e42e701728e3f3c0e4c1,windows_ie,125.37.175.*,2,2,2.0,trqRTvKaXTKfgg24JKTI,6447a7dfa30fe6eb410c91860e7c9b45,NaN,2015392487,200,200,2,0,5,a4f763f78ef3eedfe614263b94a8924e,238,5,0f951a030abdaedd733ee8d114ce2944,3427,NaN
1,0,1,20,4f51205475678f5a124bc76b2c54163bf8eaa7eb,3a1fe01360ff8100e7d006b83b77a3e4c01d928c,windows_chrome,171.36.92.*,238,239,1.0,20fc675468712705dbf5d3eda94126da,3ddf173a94bd23c326683b6373c75dd4,NaN,mm_10982364_973726_8930541,300,250,FourthView,Na,0,10722,294,23,NaN,2821,NaN
2,0,3,13,b604e3fd054a658ab7ced4285ebf2ef54d2bd890,801d18a056b6fe6b06a794aef17fb0d6daff2414,windows_ie,59.46.106.*,40,41,2.0,trqRTJn7O95I1mKYUV,625d1b5916ea925332c7b326c0574cfa,NaN,1720123646,250,250,2,0,5,798b2d49952d77f1eace9f23c210d0b5,238,24,0f951a030abdaedd733ee8d114ce2944,3427,"10052,10006,13866,10110"

# import the p_CTR

In [3]:
df_LR = pd.read_csv('pred_lr2.csv')
p_CTR = pd.DataFrame(df_LR.iloc[:,1])
p_CTR.columns = ['p_CTR']

In [4]:
print(p_CTR.shape)
p_CTR.head(n=5).T

(303925, 1)

              0         1         2         3         4
p_CTR  0.000225  0.000129  0.000096  0.000076  0.000093

In [11]:
print(df_val[df_val.click == 1].shape)
print(df_val[df_val.click == 0].shape)
df_val[df_val.click == 1].head(n=3)

p_CTR = pd.Series(df_LR.iloc[:,1])

(202, 25)
(303723, 25)

In [12]:
# all bids you have won if base bid equals to 70
bid_base = 60
print(df_val[df_val.payprice < bid_base].shape)
df_val[df_val.payprice < bid_base].head(n=5)

(138836, 25)

,click,weekday,hour,bidid,userid,useragent,IP,region,city,adexchange,domain,url,urlid,slotid,slotwidth,slotheight,slotvisibility,slotformat,slotprice,creative,bidprice,payprice,keypage,advertiser,usertag
0,0,4,20,bbcb813b6166538503d8b33a5602d7d72f6019dc,663169f66491c98c69f1f94a5c48fa34aa9fe06f,windows_ie,211.144.203.*,79,79,1.0,trqRTvFRLpscFU,5ede68cc7542a34777fb8a1574856b6f,NaN,mm_10027070_2459574_9659312,160,600,2,1,0,cb7c76e7784031272e37af8e7e9b062c,300,23,bebefa5efe83beee17a3d245e7c5085b,1458,"13866,10111"
3,0,5,15,b4d5c57c9b38ff5a12954fa01e11931b4e6bfbbb,577e9a768ce17e73c61ba7022db927f9ee761830,windows_chrome,61.187.224.*,201,205,2.0,trqRTvdJMoFoFoc4JKn,40c388f45dbc0e1fc53a8c6c81305de5,NaN,3481684581,336,280,2,0,5,dc0998c10f8f0b623b5d949e8272e4c7,238,6,d29e59bf0f7f8243858b8183f14d4412,3358,"13866,10057,10006,10063,10110"
4,0,1,18,0899bf144249458ea9c89188473694bf44c7ca15,e4bf79c562745d671b19f2edf7fda89c2e25987f,windows_chrome,117.41.145.*,134,135,2.0,tKFJeun0BouoXOl4JKTI,fcf53e0e5f09aa8d7e1c9d986cea321,NaN,1120607322,200,200,1,0,5,23485fcd23122d755d38f8c89d46ca56,249,5,7e0e909ea89f707bc20f9585c9072081,3476,"10006,10063,13776,10110"
5,0,6,1,f4c6a9a3b1db6da035c7e2a36d4f5e389095beca,5d3f7a140423324201f980609348422b7b9d2ba8,windows_ie,101.23.72.*,3,3,3.0,5KKFB19rg5scFsf,cf5d45e408ea2b18576f42a4be3865a,NaN,Lady_Width3,960,90,0,0,20,3d8f1161832704a1a34e1ccdda11a81e,241,22,b2e35064f3549d447edbbdfb1f707c8c,3427,"10063,10111"
6,0,0,18,786a2940f225482dc04d455dc7a7fea436b02e03,d29c0eb9c94d4225736a15324000b9424518abad,windows_ie,183.131.142.*,94,97,1.0,trqRTJjrXqf7FmMs,f3888d3e83f0c4f0b916af53191d8164,NaN,mm_13991432_2298120_9467354,336,280,0,1,0,13606a7c541dcd9ca1948875a760bb31,227,31,d29e59bf0f7f8243858b8183f14d4412,3358,"10006,10110"

# The Optimal Real-Time bidding strategy

In [13]:
# ORTB Bidding Function on validation set:
# ORTB = *√ c / λ x θ + c^2 − c
c_scope = np.arange(1,16,1)
lam_scope = [1e-10,5e-10,1e-9,5e-9,1e-8,5e-8,1e-7,5.2e-7,1e-6,5e-6,
             1e-5,5e-5,1e-4,5e-4,1e-3,5e-3,1e-2,5e-2,1e-1,5e-1]

ortb_bids = []
parameters = []

# seek for the all combinations of parameter to get the best ortbbids
for c in c_scope:
    for lam in lam_scope:
        parameters.append((c, lam))
        inner_eq = ((c/lam * p_CTR) + c**2 - c) 
        ortb_bid = np.sqrt(inner_eq)
        ortb_bids.append(ortb_bid.values.tolist())

In [14]:
print("The length of the parameters is:", len(parameters)) #20*15
print("The length of the ortb_bids is:", len(ortb_bids))

The length of the parameters is: 300
The length of the ortb_bids is: 300

In [15]:
import time
def ortb_bidding(bid_won):
    clicks = 0
    impressions = 0.0
    budget = 6250 * 1000
    cost = 0.0

    # bidding win procedure
    bid_won >= df_val.payprice
    for i in range(0, len(bid_won)):
        if bid_won[i] == True:
            clicks = clicks + df_val.click[i]
            impressions = impressions + 1.0
            cost = df_val.payprice[i]
            print("the bid is Within-Budget")
        if cost >= budget:
            print("the bid is Over-Budget")
            break
    return impressions, clicks, cost

In [10]:
ORTB = pd.DataFrame()
ORTB['C, Lambda'] = parameters

Impressions = []
Clicks = []
Cost = []

starttime = time.time()
print("Start ortb bidding...")

for n in ortb_bids:
    [imps, clks, ct] = ortb_bidding(n)
    Impressions.append(imps)
    Clicks.append(clks)
    Cost.append(ct)

ORTB['impressions'] = Impressions
# impression can't be a float
ORTB.impressions = ORTB.impressions.astype(int)
ORTB['cost'] = Cost
ORTB['clicks'] = Clicks
ORTB['CTP'] = (ORTB.clicks / ORTB.impressions * 100).round(4).astype(str)
ORTB['CPM'] = (ORTB.cost / ORTB.impressions * 1000).round(2).astype(str)
ORTB['CPC'] = (ORTB.cost / ORTB.clicks).round(2).astype(str)

print("ORTB bidding takes %s minutes" % round(((time.time() - starttime)/60),2) + "to finish")

Start ortb bidding...

MemoryError: